[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
check_untyped_defs = true
allow_redefinition = false
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
# disallow_untyped_calls = true
disallow_untyped_decorators = true
# disallow_untyped_defs = true
no_implicit_optional = true
strict_equality = true
warn_no_return = true
# warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

exclude = ['src/casalib/scaffolding/templates']

[tool.pylint]
disable = [
    'duplicate-code',
    'import-outside-toplevel',
]