[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
strict = true
exclude = ['src/casalib/scaffolding/templates']

[tool.pylint]
disable = [
    'duplicate-code',
    'import-outside-toplevel',
]

[tool.pylint.main]
# Fail the run if score is below this
fail-under = 9.5
# Load some stricter plugins
load-plugins = [
  # "pylint.extensions.check_docs",
  "pylint.extensions.mccabe",
]

[tool.pylint."MESSAGES CONTROL"]
# Start from "everything on"…
# enable = ["all"]

[tool.pylint.format]
max-line-length = 60

[tool.pylint.design]
max-args = 5
max-locals = 15
max-branches = 12
max-statements = 50
max-attributes = 7

[tool.pytest.ini_options]
asyncio_mode = "auto"